server:
  port: 9005

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  # h2 console
  h2:
    console:
      enabled: true

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: dispatch-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: "*"

# Custom application properties
app:
  client-service:
    url: http://localhost:8081
  notification-service:
    url: http://localhost:8086