build:
  version: 1.0.0
management:
  endpoints:
    web:
      exposure:
        include: '*'
server:
  port: 9006
spring:
  application:
    name: client-service
  datasource:
    username: sa
    url: jdbc:h2:mem:testdb
    password:
  jpa:
    properties:
      hibernate.format_sql: true
    show-sql: true
  h2:
    console:
      enabled: true
  profiles:
    active: dev
  config:
    import: "configserver:http://localhost:9007/"