build.version=1.0.0
eureka.client.fetchRegistry=true
eureka.client.registerWithEureka=true
eureka.client.serviceUrl.defaultZone=http://localhost:9008/eureka
info.app.name=client-service
info.app.description=Client service application
info.app.version=1.0.0
management.endpoints.web.exposure.include=*
management.info.env.enabled=true
server.port=9006
spring.application.name=client-service
spring.datasource.url=jdbc:mysql://localhost:3306/textile_db
spring.datasource.username=root
spring.datasource.password=12345678
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true
spring.config.import=configserver:http://localhost:9007/
